"""End-to-end persistence oracle for the block-enumerator `enumerator_format` field
(F03f / DD-99), against a LIVE Postgres.

This is the test the backend-only "green" missed: it drives the field across EVERY
boundary the operator's data actually crosses — preview (CandidateNode) → commit
(NodeRow → insert_nodes → DB) → cockpit read (fetch_nodes → ContractTreeResponse) —
and asserts `enumerator_format` survives the full DB round-trip and appears in the
tree response. A regression that drops the field at any one boundary (the original
bug) fails here, where the parse-only smoke tests passed.

Covers the four alpha/roman formats and the parenthesised-decimal `(1)(2)(3)` format
added in this change.

The body runs inside an OUTER transaction ROLLED BACK in `finally`, so the dev DB is
never mutated. Skips cleanly when no live Postgres is reachable (CI / fresh clone).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import asyncpg
import pytest
from backend.config.settings import get_settings
from backend.models.contract_tree import NodeRow
from backend.models.imports import ContractTreeResponse, NodeTreeItem
from backend.services.contract_repo import fetch_nodes, insert_nodes
from backend.services.import_.pipeline import preview_docx
from docx import Document
from docx.oxml import OxmlElement
from docx.oxml.ns import qn


def _w(tag: str) -> str:
    return qn(f"w:{tag}")


def _connect_or_skip() -> Any:
    async def _c() -> Any:
        try:
            return await asyncpg.connect(get_settings().database_url)
        except (OSError, asyncpg.PostgresError) as exc:
            pytest.skip(f"no live Postgres reachable: {exc}")

    return _c()


def _build_fixture(path: Path) -> None:
    """A decimal backbone clause + one alpha-lettered list + one parenthesised-decimal
    list, all as Word auto-numbering (numPr) — markers generated by Word, absent from
    the run text. The alpha list uses lvlText "(%1)"+numFmt=lowerLetter; the decimal
    list uses lvlText "(%1)"+numFmt=decimal (the new case). The backbone uses
    unparenthesised lvlText "%1." and must stay a clause."""
    doc = Document()
    numbering = doc.part.numbering_part.element

    def abstract(aid: str, ilvls: list[tuple[int, str, str]]) -> None:
        an = OxmlElement("w:abstractNum")
        an.set(_w("abstractNumId"), aid)
        for ilvl, num_fmt, lvl_text in ilvls:
            lvl = OxmlElement("w:lvl")
            lvl.set(_w("ilvl"), str(ilvl))
            for tag, val in (("start", "1"), ("numFmt", num_fmt)):
                el = OxmlElement(f"w:{tag}")
                el.set(_w("val"), val)
                lvl.append(el)
            t = OxmlElement("w:lvlText")
            t.set(_w("val"), lvl_text)
            lvl.append(t)
            an.append(lvl)
        numbering.insert(0, an)

    abstract("40", [(0, "decimal", "%1."), (1, "decimal", "%1.%2.")])  # backbone
    abstract("41", [(0, "lowerLetter", "(%1)")])  # alpha enumerated
    abstract("42", [(0, "decimal", "(%1)")])  # parenthesised-decimal enumerated
    for num_id, abs_id in (("40", "40"), ("41", "41"), ("42", "42")):
        num = OxmlElement("w:num")
        num.set(_w("numId"), num_id)
        ref = OxmlElement("w:abstractNumId")
        ref.set(_w("val"), abs_id)
        num.append(ref)
        numbering.append(num)

    def numbered(text: str, num_id: str, ilvl: int) -> None:
        p = doc.add_paragraph(text)
        pPr = p._p.get_or_add_pPr()
        numPr = OxmlElement("w:numPr")
        il = OxmlElement("w:ilvl")
        il.set(_w("val"), str(ilvl))
        numPr.append(il)
        nid = OxmlElement("w:numId")
        nid.set(_w("val"), num_id)
        numPr.append(nid)
        pPr.append(numPr)

    numbered("Definitions", "40", 0)
    numbered("The following obligations apply", "40", 1)
    numbered("first alpha obligation", "41", 0)
    numbered("second alpha obligation", "41", 0)
    numbered("The following conditions apply", "40", 1)
    numbered("first decimal condition", "42", 0)
    numbered("second decimal condition", "42", 0)
    doc.save(str(path))


async def _make_contract(conn: Any) -> str:
    client_id = await conn.fetchval(
        "INSERT INTO clients (name) VALUES ($1) RETURNING id", "Enum Test Client"
    )
    deal_id = await conn.fetchval(
        "INSERT INTO deals (client_id, name, position) VALUES ($1, $2, 'licensor') RETURNING id",
        client_id,
        "Enum Test Deal",
    )
    ct_id = await conn.fetchval(
        "INSERT INTO contract_types (name) VALUES ($1) RETURNING id", "Enum Test Type"
    )
    return str(
        await conn.fetchval(
            """INSERT INTO contracts (client_id, deal_id, contract_type_id, name, status, origin)
               VALUES ($1, $2, $3, $4, 'drafting', 'us') RETURNING id""",
            client_id,
            deal_id,
            ct_id,
            "Enum Test Contract",
        )
    )


def _formats_in_tree(nodes: list[NodeTreeItem]) -> list[str]:
    out: list[str] = []
    for n in nodes:
        if n.enumerator_format is not None:
            out.append(n.enumerator_format)
        out.extend(_formats_in_tree(n.children))
    return out


async def test_enumerator_format_survives_preview_commit_read(tmp_path: Path) -> None:
    src = tmp_path / "enum.docx"
    _build_fixture(src)

    conn = await _connect_or_skip()
    tx = conn.transaction()
    await tx.start()
    try:
        # 1. Preview boundary: CandidateNode must carry the captured format.
        preview = await preview_docx(src, ai=False)
        preview_fmts = sorted(n.enumerator_format for n in preview.nodes if n.enumerator_format)
        assert preview_fmts == ["decimal", "decimal", "lowerLetter", "lowerLetter"], preview_fmts

        # 2. Commit boundary: rebuild NodeRows from the preview (mirrors the frontend
        #    buildCommitNodes round-trip — the field must ride along) and persist.
        contract_id = await _make_contract(conn)
        rows = [
            NodeRow(
                index=n.index,
                parent_index=n.parent_index,
                order_index=n.order_index,
                content_type=n.content_type,
                heading=n.heading,
                body=n.body,
                table_data=n.table_data,
                plain_text=n.plain_text,
                uncertain=n.uncertain,
                role=n.role,
                has_placeholder=n.has_placeholder,
                enumerator_format=n.enumerator_format,
            )
            for n in preview.nodes
        ]
        await insert_nodes(conn, contract_id, rows)

        # 3. Cockpit read boundary: the DB round-trip must surface the field in the tree.
        stored = await fetch_nodes(conn, contract_id)
        tree = ContractTreeResponse.from_rows(contract_id, stored)
        tree_fmts = sorted(_formats_in_tree(tree.nodes))
        assert tree_fmts == ["decimal", "decimal", "lowerLetter", "lowerLetter"], tree_fmts
    finally:
        await tx.rollback()
        await conn.close()
